[package]
name = "cli"
version = "0.1.0"
edition = "2021"
authors = ["Redfire <redfire75369@hotmail.com>"]
license = "MPL-2.0"

[dependencies]
structopt = "0.3.25"
ion = { path = "../ion" }
modules = { path = "../modules" }
mozjs = { package = "mozjs", git = "https://github.com/servo/rust-mozjs" }
runtime = { path = "../runtime" }

[features]
debugmozjs = ["mozjs/debugmozjs", "ion/debugmozjs"]
