[package]
name = "cli"
version = "0.1.0"
edition = "2021"
authors = ["Redfire <redfire75369@hotmail.com>"]
license = "MPL-2.0"

[dependencies]
clap = "2.33.3"
ctrlc = { version = "3.2.1", features = ["termination"] }
ion = { path = "../ion" }
modules = { path = "../modules" }
mozjs = { package = "mozjs", git = "https://github.com/servo/rust-mozjs" }
runtime = { path = "../runtime" }

[features]
debugmozjs = ["mozjs/debugmozjs", "ion/debugmozjs"]
